apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ip92aohfb-python 
  janus-idp.io/tekton: ip92aohfb-python
  backstage.io/kubernetes-id: ip92aohfb-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ip92aohfb-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml