apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ip92aohfb-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ip92aohfb-python 
  name: ip92aohfb-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ip92aohfb-python 
